### ISSUE TITLE
Create Scientist Profiles Page

### ISSUE THREAD

**Issue by KianBadie** [KianBadie/cell-atlas#10]
Create scientist profiles appendix page. Layout will be a single page with a list of profiles. Users can expand profiles and more information will appear. Because that is a difficult concept to explain in just words, I attached a screenshot that displays the expanding which is similar in concept (but the styling will be very different).

## Screenshot of example profile from bookdown project:
![Screenshot from 2020-12-02 10-13-25](https://user-images.githubusercontent.com/18221058/100913784-16a3e080-3487-11eb-9228-6c8f77b92eff.png)
## Screenshot of expanding section (section 2 is expanded while 1 and 3 are collapsed):
![Screenshot from 2020-12-02 10-16-59](https://user-images.githubusercontent.com/18221058/100914310-beb9a980-3487-11eb-863c-dee6b2b886f2.png)

**Comment by KianBadie** [comment]
@coiko I was looking for the source of the profile blurbs, and it seems that [`12_Profiles.Rmd`](https://github.com/KianBadie/cell-atlas/blob/main/12_Profiles.Rmd) has been the source of it. Am I correct? Have the profile blurbs been directly edited through that file? Or have they been sourced from somewhere else? I did see [`ScientistProfiles.txt`](https://github.com/KianBadie/cell-atlas/blob/main/text/ScientistProfiles.txt), but that is just the names.

I believe we discussed this before, but how do you feel about having a "scientist" folder with individual markdowns representing each scientist? A profile file could look something like:
```markdown
---
img:
name:
---
Blurb about the scientist here. This scientists ... 
``` 
Or for this kind of content, do you prefer to have it all in 1 file? If we decide to go individual file for a person, I guess knowing how the profiles are sourced won't be a big deal because we are going to create a new source anyways!

Last question for now, is the layout I described in the description for this issue sound correct? I will try to have something to show today so we can have something more concrete to give feedback on

**Comment by coiko** [comment]
@KianBadie Yes, the layout you describe is perfect!  And yes, the source is the .Rmd file (that's also true for 11_Features.Rmd for the Feature Index).  We've just been editing them directly there.  For the future, yes, I like the idea of having individual files for each profile, similar to the way you created the section pages.  I think it makes a lot of sense that way.  But again, please do whatever makes the most sense / is the easiest for you.  Thanks!

**Comment by KianBadie** [comment]
@coiko Sweet! And got it, thank you for the heads up on the Feature Index as well. And sound good, individual files it is :+1: 

I have a starting point to show for the profiles page. As usual, open to all critiques/comments! The images aren't a fixed size, so the profiles are not uniform. Do you think it would look better if the profiles were more uniform? In addition, what do you prefer to happen for profiles with empty bios? Should they not have an "expand" option? Or should they have a boilerplate "This scientists does not have a profile" kind of thing? 

I'm also open to different icons for the "expand" button. I'll use the "+" as a placeholder for now as it was easy to work with because it was symmetric in it's shape.

![Peek 2020-12-02 16-08](https://user-images.githubusercontent.com/18221058/100946789-f55be800-34b8-11eb-998d-a63329bf8da8.gif)

**Comment by coiko** [comment]
@KianBadie This is fantastic!  It's exactly right.  I love the layout, the colors, and the plus-sign for the expand button.  It's all beautiful!

The non-uniform pictures are my fault - I set the longest dimension to 400px as a first pass at uniformity (since some are portrait and some landscape), but I should have made all the heights the same instead.  I can fix that easily in the files.

As for the empty profiles, you can leave them empty for now.  We asked everyone to provide their own bio, and we're hoping to get them all before launch (some people procrastinate more than others).  Grant and I are still debating what to do about those who don't get back to us in time.  (One option is to write a bio for them, and the other option is to put a placeholder like "Coming soon...")

The only thing I noticed that could be changed is to sort them alphabetically.  Also, thinking about how people might land here, if they come through a link from the video citation information on a chapter section page, could the relevant bio section be already expanded when they arrive?

**Comment by KianBadie** [comment]
@coiko Great, I'm glad you love it!

In regards to the uniformity, I see. I wouldn't have known which dimension to limit for uniformity either! If you wanted to make the heights uniform for the sake of having all the text bios uniform (like the text section always takes 50% of the space and the image takes 0%-50% of the space), then that is something that could be easily done with the code. If the uniform heights are for the sake of having the profile images uniform, then that would require the editing of the files itself. If you were to modify the files, would all the images have square dimensions? 

And for sure, I'll leave the empty bios be for now :+1: 

Will sort by last name! And yeah I think we could do something like that with the profile linking, that would be a cool feature! I have some ideas of how to implement that, but I have no concrete plan I can think off the top of my head to implement that. It seems like a straightforward feature though, so I think it is possible and reasonable to implement! I will add that to the remaining features left to implement :+1:

**Comment by coiko** [comment]
@KianBadie Great, thanks!  And the linking behavior is low priority, so please don't worry about it until after the essential stuff for the initial launch is in place and we're in the next phase of playing around with additional fun features.

As for the images, I think it makes sense to have the pictures more uniform (i.e. heads roughly the same size).  Since people sent us their preferred pictures, we probably shouldn't crop them to a uniform (square) shape, but should instead leave them in their original aspect ratio.  So if we just set the heights to be uniform and have the text take the remaining space the way you have it now, I think it will look cleaner.  It seems like the height of the picture usually determines the section height, so they should look okay regardless of whether the image is portrait or landscape.  If that sounds good to you, I can just resize the image files.

**Comment by coiko** [comment]
@KianBadie Here's a .zip of the images with uniform height if you want to see how it looks.
[bios.zip](https://github.com/KianBadie/cell-atlas/files/5637848/bios.zip)

**Comment by KianBadie** [comment]
@coiko Got it, will put that feature on the back burner for now :+1: 

And sounds good with the pictures! Sorry I didn't get back to your question yesterday, I logged off by that time. But thank you for the images, I will play around with those images today and see how things look when I make the layout closer to what you described in your comment.

**Comment by KianBadie** [comment]
@coiko Here is the profiles page using the bios with uniform height that you provided. Are you okay with some of the bios being taller than the pictures? Elizabeth Wright (shown in the gif) and Yi-Wei Chang (shown in the picture) have longer bios. If we are showing the image without cropping, and keeping all the heights the same, I'm not sure of too many ways to work around this if it is an issue. Maybe the text bio can be scroll-able once it becomes taller than the image (which is 267 pixels)? That would be really easy to implement if desired. So easy that I added a naive version of it pretty quickly and have a screenshot of it attached as the last image to this comment.

## Gif of some profiles
![Peek 2020-12-09 16-12](https://user-images.githubusercontent.com/18221058/101704589-f0a7ae80-3a39-11eb-98ad-41b649b0b6bb.gif)
## Profile with longer bio
![Screenshot from 2020-12-09 16-12-08](https://user-images.githubusercontent.com/18221058/101704619-fdc49d80-3a39-11eb-9a76-68961f50a2b5.png)
## Scrollable bios
![Screenshot from 2020-12-09 16-24-49](https://user-images.githubusercontent.com/18221058/101705144-3153f780-3a3b-11eb-84d7-36041ed4a350.png)

**Comment by coiko** [comment]
@KianBadie This is perfect!  I was going to say it's fine to have the text longer than the video but it looks so much cleaner with the scroll-bar so thank you for going the extra step and implementing that!

Thanks also for adding the function to sort by last name.  And yes, I still like the display of First Name Last Name, so I'm glad you can do that even while sorting them the other way.

**Comment by KianBadie** [comment]
@coiko Got it! Scroll bar it is! And no problem :+1: 

And got, will keep it the way it is then!

**Comment by KianBadie** [comment]
@coiko For the spacing at the bottom of the appendix pages, how much space were we thinking? I started off with this much (pictures below). Should it be more or less? Or did I get lucky on the first try?

## Screenshots
![Screenshot from 2020-12-19 13-56-39](https://user-images.githubusercontent.com/18221058/102700439-3286e080-4202-11eb-961d-cea4554d90a7.png)
![Screenshot from 2020-12-19 13-56-50](https://user-images.githubusercontent.com/18221058/102700440-331f7700-4202-11eb-9d76-67c4be3c26ca.png)

**Comment by coiko** [comment]
@KianBadie _Your amazing skills paid off_ on the first try!  It's perfect!

**Comment by KianBadie** [comment]
@coiko Haha awesome! The only other noteworthy thing about its behavior is if you're at the bottom of the page and expand something past the bottom, you have to scroll down to see it. From a couple drop-down menus I explored online, this seemed normal (as things are expanding down and the page wouldn't scroll down if the dropdown was in the middle of the screen). But I just thought I would give a heads up. Let me know if that behavior is not desired! But to be honest, even though it's simple I can see this taking some fiddling with which makes me want to put into the "get to it if I can" category. But if it has higher priority I can move things around!

![Peek 2020-12-19 14-34](https://user-images.githubusercontent.com/18221058/102701084-3289df00-4208-11eb-9d54-0f3283561e24.gif)

**Comment by coiko** [comment]
@KianBadie This feels perfectly normal for me, so let's leave it for now.  Thanks!

**Comment by KianBadie** [comment]
@coiko Awesome, sounds good!

**Comment by KianBadie** [comment]
@coiko Added links to profile pages! I also added a gif of the animation playing when the page is loaded just to show it's an option. I'm not sure if that's the preferred user experience however and if it's neat or undesired if you are coming from a link.

## Gifs
![new](https://user-images.githubusercontent.com/18221058/102702544-d2e7ff80-4218-11eb-9b91-cfa460e0764f.gif)
![Peek 2020-12-19 16-37](https://user-images.githubusercontent.com/18221058/102702545-d4192c80-4218-11eb-81ec-b35b66cecb41.gif)
![Peek 2020-12-19 16-55](https://user-images.githubusercontent.com/18221058/102702750-0166da00-421b-11eb-99a3-09596f375efe.gif)

**Comment by coiko** [comment]
@KianBadie This looks so good!  Thank you!  And I love the animation!

**Comment by KianBadie** [comment]
@coiko I was planning on adding alt text to the profile images to take another complaint away from googles accessibility checker. Something like "Profile picture of <Scientist Name>". What do you think? The alt text will be read by screen readers and will also display if the image fails to load.

**Comment by coiko** [comment]
@KianBadie Sounds great (if it's not too much work)!

**Comment by coiko** [comment]
@KianBadie Also, as a super minor point, I just noticed that while the links to the profile page work beautifully from the modal sections now (e.g. the first Learn More modal on section 2.1) , they don't go to (and expand) the tag sections.  Is that an easy global fix somewhere?  Otherwise, please don't worry about it!

**Comment by KianBadie** [comment]
@coiko Not too much work at all! It's already there now. And oh that is another good catch, thank you for getting that! It is an easy fix!
