### ISSUE TITLE
Create Phylogenetic Tree page

### ISSUE THREAD

**Issue by KianBadie** [KianBadie/cell-atlas#12]
Create Phylogenetic Tree page for the appendix section. 

Screenshot from bookdown project:
![Screenshot from 2020-12-03 16-19-53](https://user-images.githubusercontent.com/18221058/101105859-839ca080-3583-11eb-918f-b497613fe98a.png)

**Comment by KianBadie** [comment]
@coiko I created a page in similar layout to the other appendix pages. What do you think of this layout? I made this version to start us off since it was really quick to do since (thankfully, there wasn't any data to process in order to create the page).

## Gif 
![Peek 2020-12-03 17-20](https://user-images.githubusercontent.com/18221058/101109489-e1cd8180-358b-11eb-95aa-5ccf6d8924d8.gif)
## Screenshot
![Screenshot from 2020-12-03 17-20-05](https://user-images.githubusercontent.com/18221058/101109496-e5610880-358b-11eb-8477-d44271005bcb.png)

**Comment by coiko** [comment]
@KianBadie It's fantastic!  The layout is perfect.  The only tiny change would be to add another "e" in the title ("Phylogenetic" - it's a weird word).  Thank you!

**Comment by KianBadie** [comment]
@coiko Great! Haha totally a spelling error on my part. I mispelled that in a couple places and thought I corrected them all but I guess not!

**Comment by KianBadie** [comment]
@coiko I fixed the phylogenetic tree links this morning. Below is the list of links I found did not work and a list of what I changed the links to. I did this by checking the sections the original link was trying to link to and trying to find the species name in the section video citation or the modals. Let me know if any of these are incorrect!

Non-working links:
- amoebophilus asiaticus: 9-7-type-vi-secretion-contd-.html#fig:9-7a	
- bacteroidetes jt5: 10-2-tails.html#fig:10-2
- chloroflexi: 4-4-photosynthesis-contd-.html#fig:4-4
- mycobacterium marinum: 2-5-variation.html#fig:2-5
- tetrasphaera remsis: 5-5-monoderm-cytokinesis-contd-.html#fig:5-5
- acetonema longum: 4-6-microcompartments.html#fig:4-6
- sporomusa acidovorans: 8-10-diderm-sporulation-contd-.html#fig:8-10c
- staphylococcus aureus: 5-4-monoderm-cytokinesis.html#fig:5-4
- thiomonas intermedia: 5-1-segregation.html#fig:5-1
- cupriavidus necator: 4-8-storage.html#fig:4-8
- gluconacetobacter hansenii: 9-2-biofilm-contd-.html#fig:9-2
- azospirillum brasilense: 7-4-chemoreceptors.html#fig:7-4a
- rhodopseudomonas palustris: 4-3-photosynthesis.html#fig:4-3
- vibrio cholerae: 9-7-type-vi-secretion-contd-.html#fig:9-7
- halothiobacillus neapolitanus: 4-9-storage-contd-.html#fig:4-9b
- lysobacter antibioticus: 4-8-storage.html#fig:4-8a
- methyloprofundus sedimenti: 4-3-photosynthesis.html#fig:4-3a
- pseudomonas flexibilis: 6-5-flagella-patterns-contd-.html#fig:6-5
- pseudoalteromonas luteoviolacea: 9-7-type-vi-secretion-contd-.html#fig:9-7b
- proteus mirabilis: 6-5-flagella-patterns-contd-.html#fig:6-5a
- salmonella enterica (typhimurium): 7-2-chemosensory-array.html#fig:7-2
- sulfolobus acidocaldarius: 5-12-escrt-contd-.html#fig:5-12
- halohasta litchfieldiae: 4-10-archaeal-storage-granules.html#fig:4-10b
- halorubrum litoreum: 4-10-archaeal-storage-granules.html#fig:4-10
- haloferax gibbonsii: 4-10-archaeal-storage-granules.html#fig:4-10a

What I changed the links to:
- amoebophilus asiaticus: 9-7-contractile-weapons.html
- bacteroidetes jt5: 10-2-contractile-tails.html
- chloroflexi: no link
- mycobacterium marinum: 2-5-classification-exceptions.html
- tetrasphaera remsis: 5-5-monoderm-cytokinesis.html
- acetonema longum: 4-5-microcompartments.html
- sporomusa acidovorans: 8-10-diderm-spore-engulfment.html
- staphylococcus aureus: 5-4-monoderm-septum.html
- thiomonas intermedia: 5-1-copy-number.html
- cupriavidus necator: 4-7-bacterial-storage-granules.html
- gluconacetobacter hansenii: 9-2-biofilm-matrix.html
- azospirillum brasilense: 7-4-chemoreceptor-variety.html#aerotaxis
- rhodopseudomonas palustris: 4-3-intracytoplasmic-membrane.html
- vibrio cholerae: 9-7-contractile-weapons.html
- halothiobacillus neapolitanus: 4-8-storage-granule-variety.html
- lysobacter antibioticus: 4-7-bacterial-storage-granules.html
- methyloprofundus sedimenti: 4-3-intracytoplasmic-membrane.html#icm-variety
- pseudomonas flexibilis: 6-5-peritrichous-flagella.html
- pseudoalteromonas luteoviolacea: 9-7-contractile-weapons.html#macs
- proteus mirabilis: 6-5-peritrichous-flagella.html#proteus-mirabilis-flagella
- salmonella enterica (typhimurium): 7-2-chemosensory-arrays.html
- sulfolobus acidocaldarius: 5-12-cdv.html
- halohasta litchfieldiae: 4-9-archaeal-storage-granules.html#halohasta-litchfieldiae-granules
- halorubrum litoreum: 4-9-archaeal-storage-granules.html
- haloferax gibbonsii: 4-9-archaeal-storage-granules.html#haloferax-gibbonsii-granules

**Comment by coiko** [comment]
Thanks @KianBadie!  And sorry to make you go through all that!

These look great!  I found a few more in modals, so if you get a chance, you could re-update these:

- amoebophilus asiaticus: 9-7-contractile-weapons.html#t6ss-battery
- sporomusa acidovorans: 8-10-diderm-spore-engulfment.html#sporomusa-acidovorans-sporulation
- halothiobacillus neapolitanus: 4-8-storage-granule-variety.html#carboxysome-granule-connections
- lysobacter antibioticus: 4-7-bacterial-storage-granules.html#storage-granule-growth

**Comment by KianBadie** [comment]
@coiko No worries! Sorry I didn't expand on the modals. I realized that the other links wouldn't open modals so I didn't include any modal anchors in the links of the phylogenetic tree. Would you want me to add those modal tags in including the ones you just commented? My apologies, I realize that if I brought it up earlier then maybe there could have been more time to modal hunt for the tree links. I figured it would be fine for now to just have the links to the page without the anchor, but when I think about it now I should've brought it up. What do you think we should do?

**Comment by coiko** [comment]
@KianBadie No worries!  I just figured since you had modal tags for some of them, I'd add them for the others.  But don't spend any more time on it; we can definitely revisit this in the future!  (By the way, the modal-opening links from the Feature Index work fantastically!)

**Comment by KianBadie** [comment]
@coiko thank you! Do you think I should leave the anchors out for all the links? A "none or all" sort of thing? Or should I add the ones we have? 

And I'm glad! Just like the profile links, let me know if you spot any other issues anywhere. My "clean up" time has been going well so far so I can take any necessary bugs that need to be squashed.

**Comment by coiko** [comment]
@KianBadie It's totally up to you!  If it's quick and you'd like to do it, please go ahead.  (I think these are about half the total, so it's a significant chunk and might cover plenty of user's experience.)  But if you'd rather leave them out, that's totally fine.  I'm guessing the phylogenetic tree will be one of the first things we improve in V2, so maybe your bug-squashing abilities are better spent elsewhere!

The only other thing I've seen is one placeholder link I stupidly put in in the About page - it's at the end of the first "About the Project" section and it goes (or should go) to the Introduction.  Do you mind squashing that after all your more pressing bugs?
