### ISSUE TITLE
Create Introduction Page

### ISSUE THREAD

**Issue by KianBadie** [KianBadie/cell-atlas#14]
Create introduction page that is the first section of the chapter. The layout will be the same as a section page with Acknowledgements as a "Learn more" subsesction.

[Page](https://cellstructureatlas.org/book/acknowledgments.html#acknowledgments) from the bookdown site:
![Peek 2020-12-07 16-19](https://user-images.githubusercontent.com/18221058/101420928-0be2b480-38a8-11eb-8198-d1dc7098be7a.gif)

**Comment by KianBadie** [comment]
@coiko I just finished a version of this page. How does this page look to you so far? I was planning on having the content in an `introduction.md` and `acknowledgements.md` file in the root directory.

## Gif
![Peek 2020-12-07 16-15](https://user-images.githubusercontent.com/18221058/101420996-36cd0880-38a8-11eb-8d25-31d941326ad2.gif)
## Screenshots
![Screenshot from 2020-12-07 16-14-37](https://user-images.githubusercontent.com/18221058/101421005-3af92600-38a8-11eb-99dd-f2dd95e2b097.png)
![Screenshot from 2020-12-07 16-17-00](https://user-images.githubusercontent.com/18221058/101421006-3b91bc80-38a8-11eb-9474-f4c6917c3206.png)

**Comment by coiko** [comment]
@KianBadie It's perfect!  Thank you so much!

**Comment by KianBadie** [comment]
@coiko Great! I will go ahead and leave it as is then!

**Comment by KianBadie** [comment]
@coiko Is this what you were thinking of for the "landing page for the landing page"? It is only accessible by clicking the "Read Now" button from the main landing page, as it does not show up in the nav menu in any way. If you like this, what should I name the page itself? As in, what should the <Page Name> be in `cellatlasurl/<Page Name>.html`? Let me know if you think it might fit better in the nav menu as well as a chapter. In our last meeting, we mentioned possible names like "Introduction" or "Welcome" for the chapter and maybe we could use "Getting Started" for the actual introduction page if we wanted this to be in the nav menu.

## Gif
![intro](https://user-images.githubusercontent.com/18221058/102028908-29f55c80-3d61-11eb-86ce-f156210a113b.gif)
## Screenshot
![Screenshot from 2020-12-13 16-36-02](https://user-images.githubusercontent.com/18221058/102028937-4f826600-3d61-11eb-8271-847c24fd6a3b.png)

**Comment by coiko** [comment]
@KianBadie It's perfect!  That's exactly what I had in mind.  And yes, I still like the idea we discussed on Friday where this page doesn't appear in the Nav menu (just the introduction section page) and it's just a sort of passing entryway to the text.  As for a name, how about something like "begin.html"?

**Comment by KianBadie** [comment]
@coiko Perfect! I will stick with the way it is implemented then navigation wise. "begin.html" sounds good to me and I will go ahead and change that!
