### ISSUE TITLE
Create "About this Book" Page

### ISSUE THREAD

**Issue by KianBadie** [KianBadie/cell-atlas#15]
Create "About this Book" page that is accessible by clicking "About this book" text in the footer. The page will have text about the book and a google form to provide feedback on the book.

**Comment by KianBadie** [comment]
@coiko I created the page for the "About this book" content. The text content was straightforward as it has been with the other pages. However, incorporating the iframe was actually trickier than expected. I've learned that a web security policy prevents the parent window from communicating with the internal stuff of the iframe window. This prevents me from making the height of the iframe container dynamic and change depending on the internal content of the form. I made a version of the page where the height is somewhat hardcoded in so that the the height fits all the contents of the form (1st gif), but I'm not sure yet if that will be consistent for every experience. I also made a version where the iframe will always be the same height (2nd gif). However, it uses an internal scroll bar to navigate the form, which I am not sure how desirable that is. 

The background for the page also made a very short but somewhat import message about passwords from google on the form blend into the background (1st picture). I put up some pictures (2nd and 3rd picture) of making the background white and I wanted to get your opinion on this matter. The white background would look the same for both versions I mentioned in the previous paragraph. I doubt anyone would share their password on this form, but it does feel like an important message to have visible. What do you think?

Lastly, I want to propose another option for the feedback form. How do you feel about having the feedback form in a modal window? So a user would click the feedback form link, and it would open the modal with the form in it. That way, the scrolling would be contained in the modal, the height would be consistent, and the background can be white while not conflicting with the background with the rest of the page. If you are interested in this option, it would be quick because we already have the code for the modal window. I think I have a bias because of its conveniences technically, but I want to know what you think? Does this sound nice or do you think it fits better having it within the flow of the page like the Phylogenetic tree page?

## Gif of form at height trying to fit content
![full_height](https://user-images.githubusercontent.com/18221058/101551209-8b828900-3965-11eb-9ba8-1998432bfcb7.gif)
## Gif of form at fixed height with internal scrolling
![half_height](https://user-images.githubusercontent.com/18221058/101551238-96d5b480-3965-11eb-9673-cd2376924338.gif)
## Text blending into background (at the very bottom of the form)
![Screenshot from 2020-12-08 14-50-24](https://user-images.githubusercontent.com/18221058/101551572-0ea3df00-3966-11eb-8f22-556e76d7d5a8.png)
## White background
![Screenshot from 2020-12-08 14-51-55](https://user-images.githubusercontent.com/18221058/101551588-182d4700-3966-11eb-89d8-98d9517bf827.png)
![Screenshot from 2020-12-08 14-52-08](https://user-images.githubusercontent.com/18221058/101551590-18c5dd80-3966-11eb-8a72-660d5b1d855b.png)

**Comment by coiko** [comment]
@KianBadie Sorry for the pain!  It's never the things you expect.  (I had no idea about the security issue.)  Anyway, I really like your idea of putting this in a modal window (with a white background) - I think it will be nicer for the experience as well as from the technical perspective.  The other option, which is totally fine, would be to just link out to the form externally.  So if you don't want to keep wrestling with it, feel free to just drop the link in there.

If you have some extra time at some point (definitely not necessary), what do you think about putting the text content of the page into accordion sections like you did for the Profiles and Feature Index?  I think I just really like how those pages look so I'm looking for more excuses to use the accordion feature...

**Comment by KianBadie** [comment]
@coiko No apologies needed! I agree with you though that it is never the things you expect. I had no idea about the security issue either! Really though, it seems like it only affects a small part with working with iframes and doesn't hinder the overall experience of working with them. And ok! I will try things in a modal window and post some more pictures.

Yeah I think that could work! I will try that out (if I have time, like you said). I think it's a good use case for them since the text content for this page is naturally in sections. When I try that out I'll let you know how it goes! But I am glad you really enjoy the accordion pages!

**Comment by KianBadie** [comment]
@coiko I made a version with the modal screen. What are your thoughts on this? Do you like it in the flow of the about us page better, or in the modal?

## Gif
![Peek 2020-12-08 19-39](https://user-images.githubusercontent.com/18221058/101574403-8b967f00-398d-11eb-99cd-d8f3b9ef51d6.gif)
## Screenshot
![Screenshot from 2020-12-08 19-40-07](https://user-images.githubusercontent.com/18221058/101574423-8cc7ac00-398d-11eb-91e7-a659340595d5.png)

**Comment by coiko** [comment]
@KianBadie It's perfect!  I love it in the modal window.  It looks much better and doesn't disrupt the main page.  Thanks!

**Comment by KianBadie** [comment]
@coiko Awesome and no problem!

**Comment by KianBadie** [comment]
@coiko here is the page in dropdown form! Thoughts?

![Peek 2020-12-19 13-44](https://user-images.githubusercontent.com/18221058/102700207-547f6380-4200-11eb-8072-6b4981ab1fe2.gif)

**Comment by coiko** [comment]
@KianBadie I think it's perfect!  It looks great!

**Comment by KianBadie** [comment]
@coiko Finally fixed the links on this page too!

![Peek 2020-12-19 23-10](https://user-images.githubusercontent.com/18221058/102707413-879d1380-424f-11eb-8316-2798b94e0cdf.gif)

**Comment by coiko** [comment]
Beautiful!  Thanks @KianBadie!
