### ISSUE TITLE
Create Landing Page

### ISSUE THREAD

**Issue by KianBadie** [KianBadie/cell-atlas#16]
Create landing page for the website.

Picture of mock landing page:
![Screenshot from 2020-12-08 19-47-59](https://user-images.githubusercontent.com/18221058/101577097-4fafe980-398e-11eb-883a-750f6541aeb9.png)

**Comment by KianBadie** [comment]
@coiko The vertical spacing is a bit off from the mock up, but I can go back to fine tune that later. I wanted to share these screenshots before I took a break from styling this page for a bit to work on other tasks! Feel free to share any thoughts.

## Gif
![Peek 2020-12-09 11-44](https://user-images.githubusercontent.com/18221058/101679206-df4bab80-3a13-11eb-8612-a2c529547282.gif)
## Screenshot
![Screenshot from 2020-12-09 11-44-08](https://user-images.githubusercontent.com/18221058/101679214-e2df3280-3a13-11eb-8758-bf73f1ca057e.png)

**Comment by coiko** [comment]
@KianBadie Oh I love it!  It's beautiful!
