### ISSUE TITLE
Create Outlook Chapter/Section

### ISSUE THREAD

**Issue by KianBadie** [KianBadie/cell-atlas#17]
Create last chapter/section outlook.

**Comment by KianBadie** [comment]
@coiko I created the "Outlook" page and the "Keep Looking" page. How do you feel about the navigation/page titles? Do you think there should be any modifications? 

## Gif
![Peek 2020-12-14 14-34](https://user-images.githubusercontent.com/18221058/102144173-e27ed700-3e19-11eb-896b-2395fed70bc0.gif)
## Screenshot of nav menu
![Screenshot from 2020-12-14 14-34-49](https://user-images.githubusercontent.com/18221058/102144185-e90d4e80-3e19-11eb-8beb-e056b18309d4.png)
## Page Titles in browser window
![Screenshot from 2020-12-14 14-35-54](https://user-images.githubusercontent.com/18221058/102144209-f0ccf300-3e19-11eb-94f6-2e4bfdc37205.png)
![Screenshot from 2020-12-14 14-36-20](https://user-images.githubusercontent.com/18221058/102144213-f1658980-3e19-11eb-9a7e-1e44f859f3d3.png)

**Comment by coiko** [comment]
@KianBadie It's perfect!  I wouldn't change a thing.  Thank you so much!

**Comment by KianBadie** [comment]
@KianBadie Terrific!
