### ISSUE TITLE
Implement chapter pages

### ISSUE THREAD

**Issue by KianBadie** [KianBadie/cell-atlas#3]
Implement chapter landing pages.

How they currently look on the bookdown project:
![Screenshot from 2020-11-18 13-12-43](https://user-images.githubusercontent.com/18221058/99588661-cb2a0680-299f-11eb-8d04-d9d5bd652679.png)

**Comment by KianBadie** [comment]
I created a placeholder with some styling. It might not be ideal, but it can be a place for us to start off and make improvements or create a new idea all together!

![Screenshot from 2020-11-19 21-29-10](https://user-images.githubusercontent.com/18221058/99762869-542f6380-2aae-11eb-85d5-cd783631a103.png)

**Comment by KianBadie** [comment]
Based on our meeting last Friday 11/20, we decided to remove the text section and to try a layout where the quote was underneath the chapter title.

**Comment by KianBadie** [comment]
@coiko How is this looking? Any ideas/critiques/comments? I added a gif of switching to/from the page to try to simulate the "experience" of landing on the page.

![Screenshot from 2020-11-25 14-09-43](https://user-images.githubusercontent.com/18221058/100288457-8f58e900-2f2b-11eb-98a9-1c0dbbdec26e.png)
![Peek 2020-11-25 14-12](https://user-images.githubusercontent.com/18221058/100288456-8ec05280-2f2b-11eb-9ddf-9db551fccd99.gif)

**Comment by coiko** [comment]
@KianBadie Ooh, nice!  I love the full width.  It looks great.  

If you want to play around with it more (after all your more important things - this would be icing an already great cake), I can make a couple minor style suggestions to try.  I might make the title font slightly smaller, and the quote font a little larger.  And in the wide format, it would be cool to have them side-by-side (with the quote popping under the title like you have it for the narrow format).  It might look something like this?

Also, the quote might look better with the attribution on a separate line from the rest of the quote.  What do you think?
![ChapterLanding](https://user-images.githubusercontent.com/56415464/100290731-e44b2e00-2f30-11eb-8054-7ef6f5180a38.jpg)

**Comment by KianBadie** [comment]
@coiko Thank you! I would be happy to make those additions when I wrap up those other tasks. I think the image you shared looks great and I will implement those changes. And thank you for the mock ups! It makes it so much easier to understand what is desired.

**Comment by coiko** [comment]
@KianBadie I'm sorry to change this again, but I saw this and realized it looks backwards to me.  I think I flipped how it should appear.  What do you think about instead having the quote on the left and the chapter title on the right like this?

![ChapterLanding copy](https://user-images.githubusercontent.com/56415464/100679536-8f3e5c00-3324-11eb-936a-861658fd6c42.jpg)

**Comment by KianBadie** [comment]
@coiko No worries at all! It's a minor change, and if it were to change in the future it would also be another very quick edit :+1: 

To me, either is fine. I like how in the one you just created (quote on the left), the quote feels like a lead-in for the chapter and the chapter title on the right feels like I truly am about to enter the chapter. I vote for this option!

**Comment by coiko** [comment]
Awesome - thanks @KianBadie!

**Comment by KianBadie** [comment]
@coiko The first chapter summary section does not have any media associated with it. For now, I just left it blank. Do you think it should be laid out differently without the media? Or is there media on the way for this section?

## Screenshot
![Screenshot from 2020-12-13 16-06-42](https://user-images.githubusercontent.com/18221058/102028145-72ab1680-3d5d-11eb-986c-e36bf0a675a6.png)

**Comment by coiko** [comment]
@KianBadie Yep - it's on the way, so that's perfect!

**Comment by KianBadie** [comment]
@coiko Sounds good!

**Comment by KianBadie** [comment]
@coiko I reversed the spacing for the chapter sections. I figured it would be worth trying to change the styling as the screen get's smaller (since the chapter pages looked a bit wonky on narrower screens, especially after adding some of my changes). I showed how it works in the gif below. The code for it is pretty isolated, so if you think we should worry about it later and not open that can of worms I can easily remove it. I made the layout change at exactly 1280px, which was an estimate for when the screen starts looking wonky (gifs of before and after below).

Another thing I noticed is that the "Introduction" chapter landing page has a pretty long title, making it cross over the center little bit. It seems like this problem is also on the current site. What do you think of this? Do you think it should be fiddled with before launch or do you think it's minor? I think it would be something like having to reduce the font size if the width of the title is too long.

## Screenshots
![Screenshot from 2020-12-19 12-21-19](https://user-images.githubusercontent.com/18221058/102698767-b9cd5780-41f4-11eb-9c82-ee7fb4f29e62.png)
![Screenshot from 2020-12-19 12-26-41](https://user-images.githubusercontent.com/18221058/102699077-d8cce900-41f6-11eb-9a9e-b6f6ebef1df6.png)
## Gif of before (from current site)
![Peek 2020-12-19 12-18](https://user-images.githubusercontent.com/18221058/102698751-90acc700-41f4-11eb-9dab-2a30aa4e3bf6.gif)
## Gif of before (with my changes without accounting for narrower screens)
![Peek 2020-12-19 12-47](https://user-images.githubusercontent.com/18221058/102699293-71b03400-41f8-11eb-97b3-ce77bd923f65.gif)
## Gif of after (with my changes)
![Peek 2020-12-19 12-19](https://user-images.githubusercontent.com/18221058/102698753-930f2100-41f4-11eb-8899-aa741059f198.gif)

**Comment by coiko** [comment]
@KianBadie Oh how beautiful!  I love the responsive behavior in the last gif!  It's perfect!

As for the Introduction crossing the line, it's totally up to you if you want to change it.  My intuition would be to make all of the chapter titles (but not the quotes) a slightly smaller font so they match.

**Comment by KianBadie** [comment]
@coiko Great! 

As usual, I will circle back to it then since it would require some fiddling without a clear end goal (even though it would be quick). I think what you said about the title font size consistency is true too, so if I get to it I'll see how the pages look when that is decreased
