### ISSUE TITLE
Implement section pages

### ISSUE THREAD

**Issue by KianBadie** [KianBadie/cell-atlas#5]
Implement pages that will represent each section of the book. Desired features so far are:
- [ ] Video player that plays associated section video
- [ ] Text content section that contains title, book material, video metadata, subsection "learn more" buttons
- [ ] Modal windows that contain subsection content and open when "learn more" buttons are clicked
- [ ] Responsive layout (changing screen sizes/mobile)

Mockup:
![Screenshot from 2020-11-18 13-27-09](https://user-images.githubusercontent.com/18221058/99590135-cc5c3300-29a1-11eb-8c7a-d08729ac74d6.png)

**Comment by KianBadie** [comment]
Current progress so far: there is a prototype page that accepts content/metadata from different markdown files. There are also prototype modal windows that also receive their data from their own markdown files.
![Peek 2020-11-18 13-34](https://user-images.githubusercontent.com/18221058/99590850-c286ff80-29a2-11eb-835b-764ce4eb47ae.gif)

**Comment by KianBadie** [comment]
Current questions I have:
1. Not necessarily related to this specific page, but will every page of the book itself ("section pages" to "appendix pages") be contained in this blue header/grey footer window? As in, will the header/footer of the book content stay in the same position during the whole book?

**Comment by coiko** [comment]
Whatever you think best.  It's probably good to keep the header, but I think it makes sense to move the footer according to how much content is on a given page.  What do you think?

By the way, the videos showing the site behavior are awesome!

**Comment by KianBadie** [comment]
I think given the current layout/plans for the section page, it seems that the content inside the header/footer change layout in order to keep everything on the screen without the need for scrolling the entire page, but rather scrolling the content in between the header/footer. I think it would be fitting to maintain that style throughout all the "pages" of the book. When you say move the footer, how would the footer move? Move it as in increase size, or change it's location (like move further down the page)?

I'm glad you like it! I like it too because it's a lot more efficient than having to take screenshots of all the different aspects.

**Comment by coiko** [comment]
I agree.  That sounds like the best approach.  I like the idea of not scrolling the whole page.  It feels cleaner for navigation and mimics flipping consistent pages of a physical book.  It also minimizes white space (or in this case gray space) around the video.

So scratch my previous comment about moving the footer (by which I really meant scrolling all the page content).  This is much better!

**Comment by KianBadie** [comment]
@coiko sounds great! I will go ahead and implement the page with that style then

**Comment by KianBadie** [comment]
Based on our meeting last Friday 11/20, the material content of the text section (everything in between the title and the video citation section) will become scroll-able when screen sizes become narrower. The "Learn more" section will be able to take more text section real estate if needed (like if the buttons don't in one row).

**Comment by KianBadie** [comment]
@coiko Today I have been making the section pages more responsive to narrowing screens. One particular thing I had a question about was regarding the "video citation" sections. We decided that we wanted it to flow in a vertical direction when the screen gets to narrow. I made a mock of it today, and thought it might be possible that it is leaving too much open space. So I also mocked a version where the different fields of the section (name, doi, collector) wrap. I have attached screenshots below of the page on a narrow-ish size and wanted to get your opinion on it.

Also, if you see anything else on the page you wanted to give some input on, please let me know! I have been working on making the whole page more responsive, and as you can see the text section is scroll-able and the "Learn More" buttons wrap (which puts the buttons in the same situation as this video citation section of "wrap vs vertical").  We can also style the scroll bar to be something that fits with the theme of the site as well.

For the wrapping, it can wrap in different ways as well (left justified, right justified, centered, reverse).

## Original
![Screenshot from 2020-11-23 14-56-07](https://user-images.githubusercontent.com/18221058/100024945-aa492300-2d9c-11eb-9f83-8a83886409b8.png)
## Going Vertical
![Screenshot from 2020-11-23 14-55-53](https://user-images.githubusercontent.com/18221058/100024941-a917f600-2d9c-11eb-9301-e795f6f3cbbd.png)
## Wrapping
![Screenshot from 2020-11-23 14-58-51](https://user-images.githubusercontent.com/18221058/100024947-aa492300-2d9c-11eb-8585-e0695fca9bdc.png)

**Comment by KianBadie** [comment]
Was able to get a naive solution for shelfing/unshelfing text! I say naive because I very much wanted to get it done today so I did whatever I needed in the code to get it to work. It's not too messy code wise, but it could be cleaner.

![Peek 2020-11-23 17-08](https://user-images.githubusercontent.com/18221058/100033194-8f7faa00-2dae-11eb-8c85-056062e7ead8.gif)

**Comment by coiko** [comment]
@KianBadie this is beautiful!  I love the shelf behavior.  That looks exactly right.  

I also love the responsive scrolling text section.  I agree that switching straight to a vertical layout for the video citation section creates too much blank space.  I really like the field wrapping option (#2).  It looks great and should be a bit more flexible than wrapping the text in the fields (since the text, e.g. the DOI, is so long).  And I think the center justification is great.  I don't think the divider lines are necessary.  Would it simplify things to remove them entirely, even from the full-width version?  And yes, the button wrapping also looks great that way.

Looking at the page overall, the only thing I think we might be able to improve slightly is the Learn More section.  It seems to take up more real estate than it needs.  If you have time in the future and want to play around with it, maybe you could try moving the buttons in line with the "Learn More:" text.  In many cases, there are only one or two buttons, so they may all fit on one line then.  And for this example where there are three, the narrower format could have one on the top with the text and two on the bottom.  So it may often save us a (short) line.  What do you think?

**Comment by KianBadie** [comment]
@coiko Thank you! And sounds good, field wrapping with center justification it is :+1: Yes, it would actually simplify things to remove the divider lines (but adding them back wouldn't be a big deal either). I will go ahead and remove them for now and we'll see how they turn out!

Yeah I think that is a good idea and I have time to try that out! I will try that out and post some picture of how that looks.

**Comment by KianBadie** [comment]
@coiko I tried yesterday to get the buttons to wrap nicely in the way we mentioned, but it turned out to be a bit tricky for me to figure out how to get it to wrap in a way that still looked uniform and nice. I decided to stick with a placeholder wrapping style (1st gif below) for now and I will come back to revisit this once I get some other main tasks for this page done. In the second gif, I tried to make more use of the space in the learn more section, but the tricky part was trying to make the spacing look natural (especially for the 1st button once the wrapping starts). I think it's still possible, but would just take some figuring out, which is why I figured I should knock out some bigger objectives for the week first before revisiting. For both of these gifs, the parts that don't look the best are those rare sections with 3+ buttons with long names. Any input/critique/opinions appreciated!

## Current temp solution
![right_wrap](https://user-images.githubusercontent.com/18221058/100264717-0da19500-2f04-11eb-8dbe-c040691d478f.gif)
## Trying to make use of space more
![Peek 2020-11-24 12-51](https://user-images.githubusercontent.com/18221058/100264821-32960800-2f04-11eb-9017-e65b960db9e2.gif)
## An example of the temp solution looking a bit more wonky with more large buttons
![Peek 2020-11-25 09-58](https://user-images.githubusercontent.com/18221058/100265216-ca93f180-2f04-11eb-9a0e-5fbd0ce42868.gif)

**Comment by coiko** [comment]
@KianBadie Thanks for looking into this!  I like the current temp solution - it brings that section more into balance with the others.  As for the wonkiness with more/longer buttons, I think that requires a content fix from my side.  I was lazy about long titles, but I can easily make them less sloppy.  (The only alternative I can think of would be to either show an abbreviated title like "Diderm peptid..." or to use a standard icon for a learn-more button and display the title as a hover-over popup, but I think that would be annoying for the reader.)  So yes, this behavior is perfect, and I'll work on trimming the length of the titles.

**Comment by KianBadie** [comment]
@coiko No problem! And no worries about the long titles! I agree that a standardized representation of the learn more buttons would be less convenient for a reader than something more descriptive. If the abbreviated versions would just be max character count (as in "Sample Title" becomes "Sample T...") then we can implement that in the code to remove the process of renaming the current schematics/more sections as well as removing the need for someone to think about naming when creating or modifying schematic/more. If the abbreviated title is a character count, it would conveniently make all the buttons the same length. I wanted to ask, is it ideal to have the full length titles? I wouldn't want to take away from that because of some layout trickiness. If anything, we could always come back to it and go with a simpler solution like we just mentioned, as this small aspect has been successful in captivating a lot of attention (at least mine) haha.

In addition, I realized an undesirable side affect of the current temp solution. Because I tried to keep everything centered nicely, when there is only one button, it stands out as floating in the middle of the section (screenshot below to clarify). I can see some opinions liking this, but I can also see opinions thinking it's jarring. What do you think? Should the buttons be left justified if everything fits on a single row?

## Floating button
![Screenshot from 2020-11-25 14-22-59](https://user-images.githubusercontent.com/18221058/100287615-d3e38500-2f29-11eb-97b9-b7ea0c1d9795.png)

**Comment by coiko** [comment]
@KianBadie I'm of the opinion that I like the center justification!  I think it looks nice floating, especially since the "Learn More:" text will melt into the background of the reader's brain after a couple pages and they'll just focus on what's new in the buttons, which are front and center this way.  So I vote to leave it exactly as it is.

And generally, yes, I agree that you've put plenty of effort in this and we should declare victory for now and revisit it after everything else if shortening the titles turns out to be problematic (which I don't expect it to be).  Thanks for all your work on this!

**Comment by KianBadie** [comment]
@coiko I'm glad you like it, I'll stick with it then!

And sounds good to me! And just to confirm, did you want me to add a max character count to the buttons? And no problem! Thank you for being so responsive and helpful as well!

I also have one other question. I remember that each chapter was going to have its own color. I was looking at the document defining all the colors associated with the book, and each chapter has multiple colors. Is each section going to have its own color, or is it just for each chapter? If it is for each section, should I just fill in the blank in color progression for the sections that don't have a color defined? If it is each chapter, should I just pick a color that is a blend of all the colors (like how chapter 2 has been this dark blue even though the sections have a spectrum of blue)

## Colors for chapter 2 from the document I mentioned
![Screenshot from 2020-11-25 15-15-24](https://user-images.githubusercontent.com/18221058/100291165-dd70eb00-2f31-11eb-95bc-93f7792640db.png)

**Comment by coiko** [comment]
@KianBadie Don't bother adding a max character count to the buttons yet.  I think we can easily shorten the titles.  (If we run into writer's block, though, I might ask you to add that down the road.)

As for colors, thanks for checking and sorry it's confusing.  I gave you the master list that has the colors for all of the annotations in the videos, but you don't need to worry about that.  Each chapter (with all the sections) only has one color. I picked a light tone in the color family for the highlight hover-over.  It's the one that has the asterisk in each chapter (in this case, BCD3ED).  

I was thinking some more about how to implement the colors, and I'm afraid it might be a lot of work to change the whole theme for each chapter and it may not work that well visually.  For instance, yellow is really hard to read in pretty much every incarnation.  So for now maybe we should just use the different colors in the navigation menu (like in the bookdown Table of Contents) and keep the theme of the pages the current blue-green throughout.  We might just want to use a lighter, more readable version for the text links (something like HEX#6094A3).

 In the future (like the next phase of the project), it would be cool if we could have a progress bar for each chapter at the bottom of the page.  And if we did, maybe that could show the chapter color theme with a light-colored bar filling up with a darker color.  Something like this.  What do you think?
![ProgressBar](https://user-images.githubusercontent.com/56415464/100292935-e57f5980-2f36-11eb-8eb1-49e3e1402e2f.jpg)

**Comment by KianBadie** [comment]
@coiko Sounds good! 

And no worries on the master list. But that sounds good, I can use those lighter tones in the nav menu and keep the current color throughout. In the future, if you wanted to revisit changing the colors of the pages themselves (headers, buttons, etc.), it would not be that big of a work load. I was able to get that functionality incorporated in a quick experiment. I think more of the work would be in deciding good looking/accessible colors. I say this just to make the option seem more possible if it was desired!

Yeah I can get behind the progress bar, it could make the book feel a bit more interactive and take another step in setting itself apart from being a book in website form. That would be a fun addition to make too!

**Comment by KianBadie** [comment]
I just finished the first iteration of the nav menu today. I aligned the top of the nav bar with the header, while the mock up has the nav bar aligned slightly above the header. I also attached a gif of a version more inspired by the mockup. I personally think it looks cleaner aligned with the header, but please let me know any thoughts on anything you see in the screenshots/gifs! In addition, the nav bar is slightly wider than the mock up to keep long titles on a single line. Please let me know if it should be narrower!

While I was making this comment, I realized that the animation I currently have (top to bottom with very slight fade in) was not the only option and that a slide in from left to right would have been a great option as well. Which one do you think would be better? Would you like to see an example before making a comparison?

As always, please let me know any comments/necessary changes about anything you see in the screenshots/gifs. While making the nav bar, I realized there were other considerations in its functionality that might be notable (ex: stay open when visit another page, should sections of the chapter be showing somehow, ...). Right now, the current functionality is similar to the bookdown nav menu, where the only way to see sections is to click on a chapter, be transferred to that chapter page, and now the sections of the current chapter will be showing.

## Screenshot
![Screenshot from 2020-11-26 14-46-01](https://user-images.githubusercontent.com/18221058/100395590-62bdd380-2ff6-11eb-8235-bdf2387a68dc.png)
## Gif
![Peek 2020-11-26 14-46](https://user-images.githubusercontent.com/18221058/100395589-62253d00-2ff6-11eb-8034-a48bcfe39bd3.gif)
## Placed higher up
![Peek 2020-11-26 14-45](https://user-images.githubusercontent.com/18221058/100395587-618ca680-2ff6-11eb-8de0-ef65e81549c9.gif)
## Mock up
![Screenshot from 2020-11-26 14-54-14](https://user-images.githubusercontent.com/18221058/100395817-4cfcde00-2ff7-11eb-8dcb-0210209ae966.png)

**Comment by coiko** [comment]
@KianBadie This is so beautiful!  I love it.  And yes, you're completely right about both the placement (flush with the top) and the width to accommodate the longest title.  And I like the animation style from the top (it makes sense to me since that's where the icon is).

I think it makes sense to have it stay open as you visit other pages since I can imagine looking for something I remember seeing but not remembering the exact page, so clicking through a few to find it.  It would be a nice touch if the user could close it by clicking anywhere else on the page (instead of just on the nav bar icon).  Is that easy?  (If not, please don't worry about it.)

The only behavior I wonder about is having to click (and go to) a chapter head page to see the sections in it.  It feels slightly weird, but I think it might feel fine if the menu stays open.  (It never stood out to me in the bookdown.)  Anyway, we can talk more about it if it continues to feel weird.

In the meantime, happy Thanksgiving!  We're very grateful for your fantastic work (which I hope you didn't do all day today!).

**Comment by KianBadie** [comment]
@coiko Thank you, I'm glad you like it! And noted, staying open it is :+1: And having the nav bar closed if someone clicks somewhere else on the page would not be hard at all! 

And I agree with you that having to click a chapter to see the sections does not feel very smooth. I think it did not stand out in bookdown because the nav menu stays open while navigating. If I have time in the future, I would like to fiddle around with the nav menu for fun and experiment with the chapter heading expanding and showing the sections when one would hover over the chapter heading. 

And thank you! I hope you also had an enjoyable Thanksgiving, and thankfully I did not do it all day and I enjoyed the holiday!

**Comment by KianBadie** [comment]
@coiko Is the order of the "Learn more" buttons important? While doing work for the feature index page, I realized that the references in the feature index to figures in more/schematic sections were specific (ex: 2-2a). For now, I will write the code as if the order is not important, but still having the feature index link to the right schematic/more section.

**Comment by coiko** [comment]
@KianBadie Good question.  Yes, it would be ideal if they appeared in the order in which they're discussed in the text.  Sometimes one will reference information in an earlier one, so they make more sense read that way.  Would it help if I added numbers to them?

**Comment by KianBadie** [comment]
@coiko Sounds good! And I think we can do it without the numbers. I think the order of the buttons is dependent on the order of the list in the metadata of the section file. I think if the section files has metadata `subsection: [learn-more1, learn-more2]` it will appear in that order. So I just need to double check if they are in the right order and if not, I just need to edit the script that generates those files! It's possible they might even be in the right order already. I will let you know!

**Comment by coiko** [comment]
Fantastic - thanks @KianBadie!

**Comment by KianBadie** [comment]
Added auto-shelfing of text on the first play. Once the text is reopened and the video is played again, the text won't auto shelf anymore.
![Peek 2020-12-09 14-09](https://user-images.githubusercontent.com/18221058/101694588-33608b00-3a28-11eb-9bd6-abacd738b49e.gif)

**Comment by coiko** [comment]
@KianBadie Perfect!

**Comment by KianBadie** [comment]
@coiko For now, I have the `collector` fields of the video and "more" videos linking to the scientist profile page (no automatic opening of profiles yet). One thing I noticed was that some scientist do not have profiles. Is that an error on my end, or do some "collectors" not have profiles for the book?

**Comment by coiko** [comment]
Thanks @KianBadie!  The DOI linking looks perfect, and yes, that's where they're supposed to go.

There are a few collectors (most/all in Chapter 1) who don't have profiles.  It would be great if those were just left as plain text.  Let me know if you want me to manually curate those links; you have much better things to do, and I have the benefit of my notes so it would be easy.

**Comment by KianBadie** [comment]
@coiko Sounds good! I can change those myself, thank you though! The links are actually a result of the page generation so it would have to be changed through the code anyways, but it will be a very quick thing to change.

**Comment by KianBadie** [comment]
@coiko I merged all the changes you made to the content! I had a question about the ordering of the "Learn More" buttons. I noticed you rearranged the buttons for the sections to the correct order. Thank you for doing those! My question is if the bookdown section of the site has the correct order, because if so I found a difference in the order of the buttons and I wanted to know if your changes are the new correct ones or if the bookdown ones are the correct ones? 

The section is 4.3 where the [bookdown version](https://cellstructureatlas.org/book/4-3-intracytoplasmic-membrane.html) displays the schematic "Photocomplexes" first before "ICM variety", where our version is the other way around.

**Comment by coiko** [comment]
@KianBadie Thanks so much, and great catch!  Yes, the bookdown version should have the correct order, and yes, 4.3 should have photocomplexes before ICM variety.  Sorry I missed that.  There might be a few subsections that aren't in the bookdown version, but for all the ones that are there, the order hasn't changed.

**Comment by KianBadie** [comment]
@coiko No worries at all! I'll do a quick check for the other subsections!

**Comment by KianBadie** [comment]
@coiko I made use of the images in the [`movie_stills`](https://github.com/KianBadie/cell-atlas/tree/main/movie_stills) folder. These poster images are displayed if the video does not load or until the user hits play. The only downside right now is that if the video does not load, I have to find a way to make the height the image correct (the incorrect height is shown in the 3rd image). I'm assuming we should use the stills if the video does not load, but if the video does load would you want to use the movie still as the preview image or the first frame of the video (which we have been using)?

## Using the movie stills
![Screenshot from 2020-12-14 15-07-52](https://user-images.githubusercontent.com/18221058/102146759-6a66e000-3e1e-11eb-9e7c-1f134926a95c.png)
## Original (first frame of video)
![Screenshot from 2020-12-14 15-07-59](https://user-images.githubusercontent.com/18221058/102146763-6b980d00-3e1e-11eb-8232-c6d50aab19a8.png)
## Video has not loaded
![Screenshot from 2020-12-14 15-12-55](https://user-images.githubusercontent.com/18221058/102147144-20cac500-3e1f-11eb-90b3-9afb73ab9aca.png)

**Comment by coiko** [comment]
@KianBadie That's fantastic!  I still like the first frame of the video for the preview image.  But it's awesome to have the optional still if the movie doesn't load.  (And one of the future features we're thinking about would give users the option to see the still instead of the video.)  As for the height, don't worry about it.  We've redone a lot of the movies to clean things up, so I'm remaking the stills and I'll just put them onto a 16:9 canvas (I was planning to do that anyway to keep everything consistent).  Thanks!

**Comment by KianBadie** [comment]
@coiko Sorry for the delayed response. For sure! If the first frame for the preview image is preferred over using the movie still, I think I would have to look more into implementing that, as the code I used to create those images I showed are on a one or the other sort of functionality. I don't think it will be hard, but I will put it at the end of my "go back and implement if there is time" list, unless you think it should be higher! Feel free to let me know

**Comment by coiko** [comment]
@KianBadie that sounds fantastic.  Thanks!

**Comment by KianBadie** [comment]
@coiko I know we said in our meeting today that we wanted all links to display in a new page. However, when I thought about it more I realized we (or at least I) might have overlooked some links like the links in the nav menu or the "next/previous page" buttons for example. Do you want those links to open in a new page as well? Or should it still be all links (excluding anchors)?

**Comment by coiko** [comment]
@KianBadie Oh good point - definitely not those links.  How about we keep the internal/external divide so all links within the site open in the same page, and links out to other places like YouTube or the DOIs open in a new page.  Would that be easy to implement?  If not, I think we should just leave it as it is now.  Thanks!

**Comment by KianBadie** [comment]
@coiko Sounds good! And it will be easy to implement. And changing it shouldn't be too hard as well if we want to if you realized other types of links should behave differently.

**Comment by KianBadie** [comment]
@coiko I bumped the line spacing up a bit. Is this how much you thinking? Or should I do more or less? All the gifs below have the same value for the line height

Also, I am assuming the places where this applies are the text material of section pages, modal windows, and the appendix pages (excluding the feature index page). I assumed that things like the nav menu, feature index, section headers, and video citation sections have satisfying line height, but please let me know if it applies to any other sections I didn't mention!  

## Gifs of difference
![Peek 2020-12-19 10-40](https://user-images.githubusercontent.com/18221058/102696908-b4691080-41e6-11eb-8093-d2bd59645fd0.gif)
![Peek 2020-12-19 10-49](https://user-images.githubusercontent.com/18221058/102697094-dc0ca880-41e7-11eb-9653-7fae273a0cd4.gif)
![Peek 2020-12-19 10-51](https://user-images.githubusercontent.com/18221058/102697121-20984400-41e8-11eb-8921-144211fbbcb9.gif)

**Comment by coiko** [comment]
@KianBadie Oh that's perfect!  I think it's much easier to read.  And yes, I think those are exactly the sections that should/shouldn't have the increased spacing.  The only other places I thought of (which you might have already covered) are the About page, and (lower priority so if it's a pain, don't worry about it) the quotes on the chapter head pages. Thanks so much!

**Comment by KianBadie** [comment]
@coiko Awesome! The quotes are another thing I thought about after typing my earlier message. I'll go ahead and change that too (which will be easy)!

**Comment by KianBadie** [comment]
@coiko I increased the size of the videos. What do you think of this? Bigger, smaller, or just right?

## Gif showing difference
![Peek 2020-12-19 14-20](https://user-images.githubusercontent.com/18221058/102701151-e2f7e300-4208-11eb-8193-65e10a8c9445.gif)

**Comment by coiko** [comment]
@KianBadie Oh awesome!  Definitely just right!

**Comment by KianBadie** [comment]
@coiko In addition to the feature index (this was the last additional thing I wanted to fix), I also increased the height of the modals to increase readability on safari. What do you think? Should we include it in launch or does it not look too good? Should we make it wider to compensate? 

## Chrome
![Screenshot from 2020-12-20 20-25-09](https://user-images.githubusercontent.com/18221058/102739769-e079b400-4302-11eb-9806-ffa872bb1a95.png)
![Screenshot from 2020-12-20 20-25-01](https://user-images.githubusercontent.com/18221058/102739765-df488700-4302-11eb-844d-c4e2484e6c0b.png)
## Safari
<img width="1440" alt="Screen Shot 2020-12-20 at 8 24 47 PM" src="https://user-images.githubusercontent.com/18221058/102739798-f2f3ed80-4302-11eb-997f-0de1ec0b3048.png">
<img width="1440" alt="Screen Shot 2020-12-20 at 8 24 34 PM" src="https://user-images.githubusercontent.com/18221058/102739803-f4251a80-4302-11eb-808b-6de5859e9cf5.png">

**Comment by coiko** [comment]
@KianBadie Oh awesome!  I had been thinking about exactly that, but didn't want to add to your plate!  It looks perfect - please include it!

**Comment by KianBadie** [comment]
@coiko Will do!
