### ISSUE TITLE
Implement site navigation

### ISSUE THREAD

**Issue by KianBadie** [KianBadie/cell-atlas#6]
Implement navigation of site with nav menu. Originally, the nav menu progress was on the [issue](https://github.com/KianBadie/cell-atlas/issues/5) for the section page, but I will be moving progress here as there are some tasks to work on that are a bit more specific to the nav menu.

Screenshot on bookdown version of site:
![Screenshot from 2020-12-07 11-21-52](https://user-images.githubusercontent.com/18221058/101395209-78e15480-387e-11eb-9ab6-8e22a5d04638.png)

**Comment by KianBadie** [comment]
Made the nav bar stay open when using it to navigate the site.

## Gif:
![Peek 2020-12-07 11-23](https://user-images.githubusercontent.com/18221058/101395343-ac23e380-387e-11eb-88f3-bc202ac47a40.gif)

**Comment by KianBadie** [comment]
@coiko Fixed the titles in the nav bar!

![Screenshot from 2020-12-10 12-08-56](https://user-images.githubusercontent.com/18221058/101824055-8a299b80-3ae0-11eb-941a-a7d6f35480a4.png)

**Comment by coiko** [comment]
Beautiful!

**Comment by KianBadie** [comment]
@coiko I fixed a bug in the navigation where the nav menu was not accounting for the removal of chapter 4 section 4. I reordered the sections and I wanted to confirm if the section ordering in the second image is correct.

## Before
![Screenshot from 2020-12-13 18-15-53](https://user-images.githubusercontent.com/18221058/102033130-81022e00-3d6f-11eb-96be-55ac0729f46d.png)
## After
![Screenshot from 2020-12-13 18-16-06](https://user-images.githubusercontent.com/18221058/102033137-85c6e200-3d6f-11eb-8774-84f0aa19e6ff.png)

**Comment by coiko** [comment]
It's perfect - thanks @KianBadie!
